# Generated by Django 3.1.3 on 2021-05-28 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRecords',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'ProjectRecords',
            },
        ),
        migrations.CreateModel(
            name='BTRecords',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=5000)),
                ('filedata', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('NFT', models.BooleanField(default=False)),
                ('md5sum', models.CharField(blank=True, max_length=50, null=True)),
                ('User', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BTRecords',
            },
        ),
    ]
