# Generated by Django 3.1.3 on 2021-05-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btrecords',
            old_name='User',
            new_name='user_id',
        ),
    ]
