# Generated by Django 3.1.3 on 2021-05-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='btrecords',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
