# Generated by Django 3.1.3 on 2021-06-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210529_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btrecords',
            name='species',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='btrecords',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
